import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1.5 });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e).slice(0, 200)));
p.on('console', (m) => m.type() === 'error' && errs.push(m.text().slice(0, 200)));
p.on('requestfailed', (r) => errs.push('REQFAIL ' + r.url().slice(-70)));
await p.goto('https://entrolec.github.io/react-cornerstone3d/', { waitUntil: 'load', timeout: 60000 });
await p.waitForTimeout(18000);
console.log('title:', await p.title());
console.log('overlay:', await p.locator('.vp__overlay').first().innerText().catch(() => 'MISSING'));
console.log('pixels:', await p.evaluate(() => { const c = document.querySelector('.vp canvas'); if (!c) return 'no canvas'; const o = document.createElement('canvas'); o.width=c.width;o.height=c.height; const x=o.getContext('2d'); x.drawImage(c,0,0); const d=x.getImageData(0,0,o.width,o.height).data; let n=0; for(let i=0;i<d.length;i+=4) if(d[i]>8) n++; return n; }));
await p.locator('.panel').nth(1).scrollIntoViewIfNeeded();
await p.waitForTimeout(1500);
console.log('panel2 step1:', await p.locator('.stage__readouts .ind').allInnerTexts());
await p.getByRole('button', { name: '다음 →' }).click();
await p.waitForTimeout(2500);
console.log('panel2 step2:', await p.locator('.stage__readouts .ind').allInnerTexts());
await p.screenshot({ path: '/tmp/live.png' });
console.log('errors:', errs.slice(0, 6));
await b.close();
